config/routes.rb
Rails.application.routes.draw do

  get 'relationships/follower'
  get 'relationships/followed'
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
	devise_for :customers, controllers: {
  	sessions:      'customers/sessions',
  	passwords:     'customers/passwords',
  	registrations: 'customers/registrations'
	}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 root to: "homes#top"

 namespace :admins do
 	resources :comments, only:[:index, :show, :destroy]
 	resources :problems, only:[:index, :show, :destroy]
 	resources :categories, except: [:show, :new]
  resources :baby_images, only:[:index, :destroy]
  resources :baby_image_comments, only: [:index, :destroy]
  get 'homes/top' => "homes#top"
 end
#会員側
 resources  :babies do
   resource :excretions, only: [:new, :create, :edit, :update, :destroy]
   resource :body_weights, only: [:new, :create, :edit, :update, :destroy]
   resource :body_temperatures, only: [:new, :create, :edit, :update, :destroy]
   resource :mother_milks, only: [:new, :create, :edit, :update, :destroy]
   resource :milk_powders, only: [:new, :create, :edit, :update, :destroy]
   get 'history', on: :member
 end
   resources :problems,only:  [:index, :new, :show, :create, :destroy]
   resources :comments, only: [:create, :destroy] do
   	resource :likes, only: [:create, :destroy]
   end
 resources :customers, only: [:show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
 resources :baby_images do
  resources :baby_image_comments, only: [:create, :destroy]
 end
 get 'homes/about' => "homes#about"

end

app/models/admin.rb
class Admin < ApplicationRecord
	  devise :database_authenticatable, :registerable,
         :recoverable, :validatable
end

app/models/baby.rb
class Baby < ApplicationRecord
	belongs_to :customer
	has_many :body_temperatures, dependent: :destroy
	has_many :body_weights, dependent: :destroy
	has_many :excretions, dependent: :destroy
	has_many :milk_powders, dependent: :destroy
	has_many :mother_milks, dependent: :destroy
    enum sex: { man: 0, woman: 1}
    validates :baby_name,presence: true
end

app/models/baby_image.rb
class BabyImage < ApplicationRecord
	belongs_to :customer
	has_many :baby_image_comments, dependent: :destroy
	attachment :baby_image
	validates :body, presence: true, length: { in: 2..100 }
	validates :baby_image, presence: true
end

app/models/body_temperature.rb
class BodyTemperature < ApplicationRecord
	belongs_to :baby
	validates :body,presence: true,  length: { minimum: 2 }
	validates :body, numericality: true
end

app/models/body_weight.rb
class BodyWeight < ApplicationRecord
	belongs_to :baby
	validates :body,presence: true,  length: { minimum: 2 }
	validates :body, numericality: true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :problems, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :problem
	belongs_to :customer
	has_many :likes, dependent: :destroy
	validates :body, presence: true, length: { in: 5..200 }
	def favorited_by?(customer)
    likes.where(customer_id: customer.id).exists?
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        enum sex: {man: 0, woman:1}
        has_many :babies, dependent: :destroy
        has_many :comments, dependent: :destroy
        has_many :baby_image_comments, dependent: :destroy
        has_many :likes, dependent: :destroy
        has_many :problems, dependent: :destroy
        has_many :baby_images, dependent: :destroy
        has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
        has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
        has_many :following_customer, through: :follower, source: :followed
        has_many :follower_customer, through: :followed, source: :follower
        validates :name, presence: true, length: { in: 2..20 }
        attachment :image

        def follow(customer_id)
          follower.create(followed_id: customer_id)
        end
          # Customerのフォローを外す
        def unfollow(customer_id)
          follower.find_by(followed_id: customer_id).destroy
        end
          # フォローしていればtrueを返す
        def following?(customer)
          following_customer.include?(customer)
        end
end

app/models/excretion.rb
class Excretion < ApplicationRecord
	belongs_to :baby
	enum only: { うんち: 0, おしっこ: 1, どっちも: 2 }
	 # validates :only, inclusion: [0,1,2]
	 # validates :only, inclusion: {in: [true,false]}
	 # validates :only,presence: true
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :customer
	belongs_to :comment
end

app/models/milk_powder.rb
class MilkPowder < ApplicationRecord
	belongs_to :baby
	# validates :body,presence: true,  length: { minimum: 2 }
	# validates :body, numericality: true

	MilkPowder::SELECT_OPTIONS = [
		['３０〜９０' , [
			[30,30],
			[40,40],
			[50,50],
			[60,60],
			[70,70],
			[80,80],
			[90,90]
		 ]
		],
		['１００〜１９０' , [
			[100,100],
			[110,110],
			[120,120],
			[130,130],
			[140,140],
			[150,150],
			[160,160],
			[170,170],
			[180,180],
			[190,190]
		 ]
		],
		['２００〜３００' ,[
			[200,200],
			[210,210],
			[220,220],
			[230,230],
			[240,240],
			[250,250],
			[260,260],
			[270,270],
			[280,280],
			[290,290],
			[300,300]
		 ]
		]
	]
end

app/models/mother_milk.rb
class MotherMilk < ApplicationRecord
	belongs_to :baby
end

app/models/problem.rb
class Problem < ApplicationRecord
	belongs_to :customer
	belongs_to :category
	has_many :comments, dependent: :destroy
	validates :body, presence: true, length: { in: 10..300 }

	def self.search(search,problem_name)
	    if search
	     	  Problem.where(['body LIKE ?', "%#{search}%"])
	    elsif problem_name
	   		  category_ids = Category.where("problem_name = ?", problem_name).pluck(:id)
			  Problem.where("category_id IN (?)",category_ids )
	    else
	          Problem.all
	    end
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "Customer"
	belongs_to :followed, class_name: "Customer"
end

app/controllers/admins/baby_images_controller.rb
class Admins::BabyImagesController < ApplicationController

  def index
    @baby_images = BabyImage.all.order(created_at: "DESC")
  end

  def show
    @baby_image = BabyImage.find(params[:id])
    @baby_image_comment = BabyImageComment.new
  end

  def destroy
    @baby_image = BabyImage.find(params[:id])
    @baby_image.destroy
    redirect_to admins_baby_images_path
  end
end

app/controllers/baby_images_controller.rb
class BabyImagesController < ApplicationController
  def index
    @baby_images = BabyImage.all.order(created_at: "DESC")
  end

  def show
    @baby_image = BabyImage.find(params[:id])
    @baby_image_comment = BabyImageComment.new
  end

  def new
    @baby_image = BabyImage.new
  end

  def create
    @baby_image = BabyImage.new(baby_image_params)
    @baby_image.customer_id = current_customer.id
    if @baby_image.save
       redirect_to baby_images_path
    else
      render :new
    end
  end

  def edit
    @baby_image = BabyImage.find(params[:id])
  end

  def update
    @baby_image = BabyImage.find(params[:id])
    if @baby_image.update(baby_image_params)
        redirect_to baby_images_path
    else
      render :edit
    end
  end

  def destroy
    @baby_image = BabyImage.find(params[:id])
    @baby_image.destroy
    redirect_to request.referer
  end
  private
  def baby_image_params
    params.require(:baby_image).permit(:customer_id, :baby_image, :body)
  end
end

app/helpers/admins/baby_images_helper.rb
module Admins::BabyImagesHelper
end

app/helpers/baby_images_helper.rb
module BabyImagesHelper
end

app/helpers/babys_helper.rb
module BabysHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communitys_helper.rb
module CommunitysHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/admins/baby_images/index.html.erb
<div class="container">
	<h3 class="hiroba">Baby自慢室</h3>
	<h4 style="color:red;">※不適切な画像を削除してください</h4>
	<div class="baby-images">
		<% @baby_images.each do |image| %>
			<div class="baby-image">
				<%= attachment_image_tag image,:baby_image, :fill,150,150,format: 'jpeg' %>
				<div class="image-name"><%= "by" + image.customer.name %>
				<%= link_to "削除",  admins_baby_image_path(image),method: :delete %></div>
			</div>
		<% end %>
	</div>
</div>

app/views/baby_images/edit.html.erb
<div class="container">
	<div class="modal2">
		<h3>画像編集フォーム</h3>
		<%= form_for(@baby_image) do |f| %>
			<%= attachment_image_tag @baby_image,:baby_image, :fill,500,300,format: 'jpeg' ,class: "edit-image" %>
			<%= f.attachment_field :baby_image, class: "baby_image_field" %>
			<%= f.text_area :body, placeholder: "画像の説明",class: "caption" %><br>
			<%= f.submit 'Create', class: "image-btn" %>
		<% end %>
	</div>
</div>

app/views/baby_images/index.html.erb
<div class="container">
	<h2 class="hiroba">自慢の赤ちゃんを投稿しよう！！</h2>
	<%= link_to "Let's Post !", new_baby_image_path,class: "btn btn-default" %>
	<div class="baby-images">
		<% @baby_images.each do |image| %>
			<div class="baby-image">
				<%= link_to baby_image_path(image) do %>
				<%= attachment_image_tag image,:baby_image, :fill,150,150,format: 'jpeg' %>
				<% end %>
				<div class="image-name"><%= "by" + image.customer.name %></div>
			</div>
		<% end %>
	</div>
</div>

app/views/baby_images/new.html.erb
<div class="container">
	<div class="modal2">
		<h3>画像投稿フォーム</h3>
		<div>
		<%= form_for (@baby_image) do |f| %>
		    <% if @baby_image.errors.any? %>
                <% @baby_image.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
            <% end %>
        </div>
			<%= f.attachment_field :baby_image, class: "baby_image_field" %>
			<%= f.text_area :body, placeholder: "コメント",class: "caption" %><br>
			<%= f.submit 'Post', class: "image-btn" %>
		<% end %>
	</div>
</div>

app/views/baby_images/show.html.erb
<div class="container">
	<div style="padding-top:50px"><%= @baby_image.created_at.strftime('%Y/%m/%d') %></div>
		<%= attachment_image_tag @baby_image,:baby_image, size: "1200x700",format: 'jpeg' %>
	<div class="image-customer">
		<%= link_to customer_path(@baby_image.customer_id) do %>
		<%= attachment_image_tag @baby_image.customer,:image, :fill,80,80,format: 'jpeg' ,fallback: "no_image.jpg",class: "baby-customer-image" %>
		<% end %>
		<span><%= @baby_image.body %></span>
		<div><%= "by" + @baby_image.customer.name %></div>
		<% if @baby_image.customer_id == current_customer.id %>
			<%= link_to "Edit", edit_baby_image_path(@baby_image) %>
		<% end %>
		<span class="fa fa-comment"><%= @baby_image.baby_image_comments.count %></span>
		<button class="problem-comment-btn">コメントする</button>
	</div>

	<div class="baby-comment-area">
		<div class="problem-comment-box">
			<h3>コメント投稿フォーム</h3>
			<%= form_for [@baby_image, @baby_image_comment] do |f| %>
			<% if @baby_image_comment.errors.any? %>
                  <% @baby_image_comment.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
               <% end %>
               <% end %>
				<%= f.text_area :body , required: true %><br>
				<%= f.submit 'Post' ,class: "problem_btn" %>
			<% end %>
		</div>
		<% @baby_image.baby_image_comments.each do |baby_comment| %>
			<div class="comment-content">
				<%= link_to customer_path(baby_comment.customer_id) do %>
				<%= attachment_image_tag baby_comment.customer,:image, :fill,50,50,format: 'jpeg',fallback: "no_image.jpg" ,class: "customer-image" %></span>
				<% end %>
				<%= baby_comment.created_at.strftime('%Y/%m/%d') %><br>
				<span class="comment-body"><%= baby_comment.body %></span>
				<% if baby_comment.customer_id == current_customer.id %>
					<%= link_to baby_image_baby_image_comment_path(baby_comment.baby_image,baby_comment) ,method: :delete do %>
					<i class="far fa-trash-alt"></i>
					<% end %>
				<% end %>
			</div>
		<% end %>
	</div>
</div>