config/routes.rb
Rails.application.routes.draw do

  get 'relationships/follower'
  get 'relationships/followed'
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
	devise_for :customers, controllers: {
  	sessions:      'customers/sessions',
  	passwords:     'customers/passwords',
  	registrations: 'customers/registrations'
	}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 root to: "homes#top"

 namespace :admins do
 	resources :comments, only:[:index, :show, :destroy]
 	resources :problems, only:[:index, :show, :destroy]
 	resources :categories, except: [:show, :new]
  resources :baby_images, only:[:index, :destroy]
  resources :baby_image_comments, only: [:index, :destroy]
  get 'homes/top' => "homes#top"
 end
#会員側
 resources  :babies do
   resource :excretions, only: [:new, :create, :edit, :update, :destroy]
   resource :body_weights, only: [:new, :create, :edit, :update, :destroy]
   resource :body_temperatures, only: [:new, :create, :edit, :update, :destroy]
   resource :mother_milks, only: [:new, :create, :edit, :update, :destroy]
   resource :milk_powders, only: [:new, :create, :edit, :update, :destroy]
   get 'history', on: :member
 end
   resources :problems,only:  [:index, :new, :show, :create, :destroy]
   resources :comments, only: [:create, :destroy] do
   	resource :likes, only: [:create, :destroy]
   end
 resources :customers, only: [:show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
 resources :baby_images do
  resources :baby_image_comments, only: [:create, :destroy]
 end
 get 'homes/about' => "homes#about"

end

app/models/baby.rb
class Baby < ApplicationRecord
	belongs_to :customer
	has_many :body_temperatures, dependent: :destroy
	has_many :body_weights, dependent: :destroy
	has_many :excretions, dependent: :destroy
	has_many :milk_powders, dependent: :destroy
	has_many :mother_milks, dependent: :destroy
    enum sex: { man: 0, woman: 1}
    validates :baby_name,presence: true
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
	before_action :authenticate_customer!
	def index
	    @babies = current_customer.babies
	end
	def new
		@baby = Baby.new
	end
	def show
		@baby = Baby.find(params[:id])
		@babies = Baby.all
	    @body_weight = BodyWeight.new
	end
	def create
		baby = Baby.new(baby_params)
		baby.customer_id = current_customer.id
	    if baby.save
		   redirect_to babies_path
		else render :new
		end
	end
	def edit
		@baby = Baby.find(params[:id])
	end
	def update
		@baby = Baby.find(params[:id])
		if @baby.update(baby_params)
			redirect_to babies_path
		else render :edit
		end
	end
	def destroy
		@baby = Baby.find(params[:id])
		@baby.destroy
		redirect_to babies_path
	end
	def history
		@baby = Baby.find(params[:id])
		@date = params[:date] || Time.zone.today
		@body_temperatures = BodyTemperature.where(created_at: @date.in_time_zone.all_day).where(baby_id: @baby).order('body_temperatures.created_at asc')
		@body_weights = BodyWeight.where(created_at: @date.in_time_zone.all_day).where(baby_id: @baby).order('body_weights.created_at asc')
		@excretions = Excretion.where(created_at: @date.in_time_zone.all_day).where(baby_id: @baby).order('excretions.created_at asc')
		@milk_powders = MilkPowder.where(created_at: @date.in_time_zone.all_day).where(baby_id: @baby).order('milk_powders.created_at asc')
		@mother_milks = MotherMilk.where(created_at: @date.in_time_zone.all_day).where(baby_id: @baby).order('mother_milks.created_at asc')
		# @array =  Array.new
		# @body_temperatures.each do |body_temperature|
		# 	@array << body_temperature
		# end
		# @body_weights.each do |body_weight|
		# 	@array << body_weight
		# end
		# @milk_powders.each do |milk_powder|
		# 	@array << milk_powder
		# end
		# @excretions.each do |excretion|
		# 	@array << excretion
		# end
		# @mother_milks.each do |mother_milk|
		# 	@array << mother_milk
		# end
	end
	private
	def baby_params
		params.require(:baby).permit(:sex, :birth, :baby_name, :customer_id)
 	end
end

app/helpers/babys_helper.rb
module BabysHelper
end

app/views/babies/edit.html.erb
<div class="container">
	<div class="modal1">
			<h2>赤ちゃんの編集</h2>
				<%= form_for(@baby) do |f| %>
				  <% if @baby.errors.any? %>
			          <% @baby.errors.full_messages.each do |message| %>
			            <li><%= message %></li>
			          <% end %>
			      <% end %>
					<label>お名前</label>
					<%= f.text_field :baby_name %><br>
					<%= f.label :お誕生日 %>
					<%= raw sprintf(
						f.date_select(
						:birth,
						use_month_numbers: true,
						start_year: 2020,
						end_year: (Time.now.year - 18),
						default: Date.new(2020, 1, 1),
						date_separator: '%s'),
					'年' , '月') + '日'%><br>
					<label>性別</label>
					<label><%= f.radio_button :sex, "man" ,required: true  %> 男の子 </label>
					<label><%= f.radio_button :sex, "woman" %> 女の子</label><br>
					<%= f.submit '保存する' ,class: "btn btn-primary" %>
				<% end %>
			<%= link_to '赤ちゃん選択画面', babies_path %>
	</div>
</div>

app/views/babies/history.html.erb
<div class="container">
	<%= form_with url: history_baby_path(@baby), method: :get, local: true do |f| %>
		<div class="history-date">
	     <%= f.date_field :date, value: @date %>
	     <%= f.submit "検索する" ,class: "btn btn-info" %>
	 	</div>
	<% end %>
	<%= link_to "記録ページへ戻る", baby_path(@baby) %>
	<table class="table">
		<th>記録</th>
		<% @body_temperatures.each do |body_temperature| %>
			<tr>
				<td><%= body_temperature.created_at.strftime("%H:%M") %></td>
				<td>体温<%= body_temperature.body %>℃</td>
				<td><%= link_to "編集", edit_baby_body_temperatures_path(@baby,baby_id: body_temperature.id ) %></td>
				<td><%= link_to baby_body_temperatures_path(body_temperature), method: :delete do %>
				<i class="far fa-trash-alt"></i></td>
				<% end %>
			</tr>
		<% end %>

		<% @body_weights.each do |body_weight| %>
			<tr>
				<td><%= body_weight.created_at.strftime("%H:%M") %></td>
				<td>体重<%= body_weight.body %>KG</td>
				<td><%= link_to "編集", edit_baby_body_weights_path(@baby,baby_id: body_weight.id ) %></td>
				<td><%= link_to baby_body_weights_path(body_weight), method: :delete do %>
				<i class="far fa-trash-alt"></i></td>
				<% end %>
			</tr>
		<% end %>

		<% @excretions.each do |excretion| %>
			<tr>
				<td><%= excretion.created_at.strftime("%H:%M") %></td>
				<td><%= excretion.only %></td>
			<% if excretion.body.present? %>
				<td>内容<%= excretion.body %></td>
			<% end %>
				<td><%= link_to "編集", edit_baby_excretions_path(@baby,baby_id: excretion.id ) %></td>
				<td><%= link_to baby_excretions_path(excretion), method: :delete do %>
				<i class="far fa-trash-alt"></i></td>
				<% end %>
			</tr>
		<% end %>
		<% @milk_powders.each do |milk_powder| %>
			<tr>
				<td><%= milk_powder.created_at.strftime("%H:%M") %></td>
				<td>ミルク<%= milk_powder.body %>CC</td>
				<td><%= link_to "編集", edit_baby_milk_powders_path(@baby,baby_id: milk_powder.id ) %></td>
				<td><%= link_to baby_milk_powders_path(milk_powder), method: :delete do %>
				<i class="far fa-trash-alt"></i></td>
				<% end %>
			</tr>
		<% end %>

		<% @mother_milks.each do |mother_milk| %>
			<tr>
				<td><%= mother_milk.created_at.strftime("%H:%M") %></td>
				<% if mother_milk.body.present? %>
					<td>母乳<%= mother_milk.body %>CC</td>
					<% else %>
					<td>母乳</td>
				<% end %>
				<td><%= link_to "編集", edit_baby_mother_milks_path(@baby,baby_id: mother_milk.id ) %></td>
				<td><%= link_to baby_mother_milks_path(mother_milk), method: :delete do %>
				<i class="far fa-trash-alt"></i></td>
				<% end %>
			</tr>
		<% end %>
	</table>
</div>

app/views/babies/index.html.erb
<div class="container">
	<div class="modal1">
        <h2>SELECT BABY</h2>
			<table class="table">
				<tbody>
				 	<% @babies.each do |baby| %>
						<tr>
							 <td><%= baby.baby_name +  "(" + baby.sex + ")" %></td>
							 <td><%= link_to "選択",  baby_path(baby.id) %></td>
							 <td><%= link_to "編集", edit_baby_path(baby.id) %></td>
							 <td><%= link_to "削除", baby_path(baby.id), method: :delete, data: { confirm: '本当に消しますか？' } %></td>
						</tr>
					<% end %>
				</tbody>
				<tr>
					<td><%= link_to "赤ちゃんを追加", new_baby_path ,class: "btn btn-default"%></td>
				</tr>
			</table>
	</div>
</div>

app/views/babies/new.html.erb
<div class="container">
  <div class="modal1">
      <h2>赤ちゃん登録</h2>
        <%= form_for(@baby) do |f| %>
          <% if @baby.errors.any? %>
              <% @baby.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
          <% end %>
          <div class="baby-modal">
              <label class="baby-modal" >お名前</label>
              <%= f.text_field :baby_name %><br>
              <label class="baby-modal">お誕生日</label>
             	<%= raw sprintf(
                f.date_select(
                  :birth,
                  use_month_numbers: true,
                  start_year: 2020,
                  end_year: (Time.now.year - 18),
                  default: Date.new(2020, 1, 1),
                  date_separator: '%s'),
                '年 ', '月 ') + '日' %><br>
            	<label class="baby-modal" >性別</label>
            	<label><%= f.radio_button :sex, "man" ,{:checked => true}%> 男の子 </label>
            	<label><%= f.radio_button :sex, "woman" %> 女の子</label><br>
            	<%= f.submit 'Create',class: "btn btn-primary btn2"  %>
          </div>
        <% end %>
  </div>
</div>

app/views/babies/show.html.erb
<!-- <style>
	#RealtimeClockArea2{
		display:none;
	}
</style>
<div id="RealtimeClockArea2" >

</div> -->

<div class="container">
		<div class="items">
			<div class="item first-item"><%= link_to new_baby_mother_milks_path(@baby) do  %>
				<%= image_tag 'mother-milk2.jpg' %>
				<p class="first-p mothermilk">母乳</p>
				<p class="second-p mothermilk2">Mother Milk</p>
			<% end %>
			</div>
			<div class="item first-item"><%= link_to new_baby_milk_powders_path(@baby) do %>
				<%= image_tag 'powder-milk2.jpg' %>
				<P class="first-p">ミルク</P>
				<p class="second-p">Milk Powder</p>
			<% end %>
			</div>
			<div class="item first-item"><%= link_to new_baby_excretions_path(@baby) do %>
				<%= image_tag 'excretion4.jpg' %>
				<p class="first-p">おむつ</p>
				<p class="second-p">Excretion</p>
			<% end %>
			</div>
			<div class="item socond-item"><%= link_to new_baby_body_weights_path(@baby) do %>
				<%= image_tag 'body-weight2.jpg' %>
				<p class="first-p">体重</p>
				<p class="second-p">Weight</p>
			<% end %>
			</div>
			<div class="item socond-item"><%= link_to new_baby_body_temperatures_path(@baby) do %>
				<%= image_tag 'body-temperature2.jpg' %>
				<p class="first-p">体温</p>
				<p class="second-p">Temperature</p>
			<% end %>
			</div>
			<div class="item socond-item"><%= link_to history_baby_path(@baby) do %>
				<%= image_tag 'history2.jpg' %>
				<P class="first-p">履歴</P>
				<p class="second-p">History</p>
			<% end %>
			</div>
		</div>
</div>